### ISSUE TITLE
TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by costia123** [startxfr/siren2tva#2]
Hi, 
I have an error when i use this code :
`import siren2tva from 'siren2tva';`

`siren2tva({' longCode: true '});`

`console.log(siren2tva.siret2tva('422453217'));`

`siren2tva.getInfoCapital('422453217', function (err, capital) {
	console.log(capital);
	});`
	
	Error : 
![err](https://user-images.githubusercontent.com/78858057/117683327-408acd00-b1b4-11eb-98b0-a75e0bf2accd.PNG)

If anyone can help me you will make my day :)

**Comment by startxfr** [comment]
Hi @costia123,

Sorry for this later (and probably too late ;) answer, but release https://github.com/startxfr/siren2tva/releases/tag/1.1.6 should fix this issue.
